var geojson_CommunityClub = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "OBJECTID": 65.000000, "ADDRESSBLO": "10", "ADDRESSBUI": null, "ADDRESSPOS": "529915", "ADDRESSSTR": "Simei Street 2", "DESCRIPTIO": "Community Club", "HYPERLINK": "http:\/\/one.pa.gov.sg\/CRMSPortal\/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFPAOrgSelection&wlpCRMSPortal_1_ProgramType=1&_pageLabel=CRMSPortal_page_1", "NAME": "Changi Simei CC", "PHOTOURL": "https:\/\/one.pa.gov.sg\/CRMSPortal\/photos\/Common\/Photos_of_BU\/BU_4370.jpg", "ADDRESSFLO": null, "ADDRESSUNI": null, "POI_Code": 1.000000, "type": "cc" }, "geometry": { "type": "Point", "coordinates": [ 103.955130, 1.344774 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 78.000000, "ADDRESSBLO": "866A", "ADDRESSBUI": null, "ADDRESSPOS": "521866", "ADDRESSSTR": "Tampines Street 83", "DESCRIPTIO": "Community Club", "HYPERLINK": "http:\/\/one.pa.gov.sg\/CRMSPortal\/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFPAOrgSelection&wlpCRMSPortal_1_ProgramType=1&_pageLabel=CRMSPortal_page_1", "NAME": "Tampines Central CC", "PHOTOURL": "https:\/\/one.pa.gov.sg\/CRMSPortal\/photos\/Common\/Photos_of_BU\/BU_5590.jpg", "ADDRESSFLO": "2", "ADDRESSUNI": "1", "POI_Code": 1.000000, "type": "cc" }, "geometry": { "type": "Point", "coordinates": [ 103.934315, 1.355421 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 79.000000, "ADDRESSBLO": "13", "ADDRESSBUI": null, "ADDRESSPOS": "529453", "ADDRESSSTR": "Tampines Street 11", "DESCRIPTIO": "Community Club", "HYPERLINK": "http:\/\/one.pa.gov.sg\/CRMSPortal\/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFPAOrgSelection&wlpCRMSPortal_1_ProgramType=1&_pageLabel=CRMSPortal_page_1", "NAME": "Tampines Changkat CC", "PHOTOURL": "https:\/\/one.pa.gov.sg\/CRMSPortal\/photos\/Common\/Photos_of_BU\/BU_4390.jpg", "ADDRESSFLO": "1", "ADDRESSUNI": "5", "POI_Code": 1.000000, "type": "cc" }, "geometry": { "type": "Point", "coordinates": [ 103.947715, 1.345862 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 80.000000, "ADDRESSBLO": "10", "ADDRESSBUI": null, "ADDRESSPOS": "529341", "ADDRESSSTR": "Tampines Street 23", "DESCRIPTIO": "Community Club", "HYPERLINK": "http:\/\/one.pa.gov.sg\/CRMSPortal\/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFPAOrgSelection&wlpCRMSPortal_1_ProgramType=1&_pageLabel=CRMSPortal_page_1", "NAME": "Tampines East CC", "PHOTOURL": "https:\/\/one.pa.gov.sg\/CRMSPortal\/photos\/Common\/Photos_of_BU\/BU_5610.jpg", "ADDRESSFLO": null, "ADDRESSUNI": null, "POI_Code": 1.000000, "type": "cc" }, "geometry": { "type": "Point", "coordinates": [ 103.954623, 1.353220 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 81.000000, "ADDRESSBLO": "2", "ADDRESSBUI": null, "ADDRESSPOS": "529204", "ADDRESSSTR": "Tampines Street 41", "DESCRIPTIO": "Community Club", "HYPERLINK": "http:\/\/one.pa.gov.sg\/CRMSPortal\/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFPAOrgSelection&wlpCRMSPortal_1_ProgramType=1&_pageLabel=CRMSPortal_page_1", "NAME": "Tampines North CC", "PHOTOURL": "https:\/\/one.pa.gov.sg\/CRMSPortal\/photos\/Common\/Photos_of_BU\/BU_5250.jpg", "ADDRESSFLO": null, "ADDRESSUNI": null, "POI_Code": 1.000000, "type": "cc" }, "geometry": { "type": "Point", "coordinates": [ 103.946651, 1.357273 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 82.000000, "ADDRESSBLO": "5", "ADDRESSBUI": null, "ADDRESSPOS": "529705", "ADDRESSSTR": "Tampines Avenue 3", "DESCRIPTIO": "Community Club", "HYPERLINK": "http:\/\/one.pa.gov.sg\/CRMSPortal\/CRMSPortal.portal?_nfpb=true&_st=&_windowLabel=CRMSPortal_1&_urlType=render&_mode=view&wlpCRMSPortal_1_action=CMFPAOrgSelection&wlpCRMSPortal_1_ProgramType=1&_pageLabel=CRMSPortal_page_1", "NAME": "Tampines West CC", "PHOTOURL": "https:\/\/one.pa.gov.sg\/CRMSPortal\/photos\/Common\/Photos_of_BU\/BU_5630.jpg", "ADDRESSFLO": null, "ADDRESSUNI": null, "POI_Code": 1.000000, "type": "cc" }, "geometry": { "type": "Point", "coordinates": [ 103.935526, 1.348913 ] } }
]
}
